### ISSUE TITLE
Test crashes.

### ISSUE THREAD

**Issue by hllhll** [ua-parser/uap-go#10]
Used as-is it crashes, any perquisites that are not mentioned in the readme?

**Comment by elsigh** [comment]
No stack-trace no other info and can't repro.
You do need ua-parser/ua-core and particularly the regexes.yaml file. 

This repo could definitely use more of a README/walkthrough. But it has an example.go that isn't that cryptic.

**Comment by hllhll** [comment]
I thought there's no need to. it crashes using the latest (at that time)
regexes file. older one worked fine, guess there either some issues with
the newer additions or the way go specifically handles newer additions
(since go evaluates all the regex in advance, unlike node for exmp.)
