### ISSUE TITLE
regexes.yaml appears to be broken at HEAD with the go implementation

### ISSUE THREAD

**Issue by elsigh** [ua-parser/uap-go#11]
panic: regexp: Compile(`(008|Altresium|Argus|BaiduMobaider|BoardReader|DNSGroup|DataparkSearch|EDI|Goodzer|Grub|INGRID|Infohelfer|LinkedInBot|LOOQ|Nutch|PathDefender|Peew|PostPost|Steeler|Twitterbot|VSE|WebCrunch|WebZIP|Y!J-BR[A-Z]|YahooSeeker|envolk|sproose|wminer)/(\d+)(?:\.(\d+)(?:\.(\d+))?)?(?:(?!CFNetwork).)*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`

I will also file this on uap-core

**Comment by hllhll** [comment]
Please reference the uap-core ticket I think that would be helpful (As I encounter the same error, Go crashes when trying to compile the HEAD version)

**Comment by elsigh** [comment]
Oh, I should probably update the pinned submodule version

**Comment by elsigh** [comment]
Fixed by #20
