### ISSUE TITLE
How can I get "Brand" and "Model" from user-agent ? 

### ISSUE THREAD

**Issue by jenerd** [ua-parser/uap-go#16]
How can I get "Brand" and "Model" from user-agent ? as Deivce struct only contain "Family" field.

``` 
type Device struct {
	Family string
}
```

**Comment by mrjgreen** [comment]
I have a fork here that does this. Not passing all tests yet, due to new fields I think, but will PR when I've fixed them. Seems to work though.

https://github.com/mrjgreen/uap-go/blob/master/uaparser/device.go

**Comment by elsigh** [comment]
Yeah, if you add the parsing for it I'll be more than happy to take a PR here =)

**Comment by elsigh** [comment]
This is a dupe of Issue #13
