### ISSUE TITLE
Submodules is using ssh instead of https

### ISSUE THREAD

**Issue by fastest963** [ua-parser/uap-go#34]
Since the submodule is using ssh, that means that wherever you do `go get` that box requires an SSH public key on a Github account. This is problematic on our build server.
Instead if you used: `https://github.com/ua-parser/uap-go.git` then it would just get it over https and not require any keys.

**Comment by elsigh** [comment]
Sounds like a nearly trivial pull request 😉

**Comment by fastest963** [comment]
Added a PR. Thanks!
