### ISSUE TITLE
AppInsights is wrongly recognized as IE on Windows.

### ISSUE THREAD

**Issue by hsluoyz** [ua-parser/uap-go#56]
Hi @elsigh 

The user agent is:

```
Mozilla/5.0+(compatible;+MSIE+9.0;+Windows+NT+6.1;+Trident/5.0;+AppInsights)
```

which is clearly a bot. But it is recognized by uap-go as:

![image](https://user-images.githubusercontent.com/3787410/50580528-828c0180-0e8a-11e9-8633-6cda83236322.png)

Can we fix it? Thanks.

**Comment by elsigh** [comment]
Anyone can submit a PR to fix the issue =)

**Comment by elsigh** [comment]
But this is really an issue (and the fix belongs) in https://github.com/ua-parser/uap-core
