### ISSUE TITLE
Parser panics on the latest version of `regexes.yaml` from `uap-core` (v0.7.0)

### ISSUE THREAD

**Issue by laingawbl** [ua-parser/uap-go#66]
When parsing the newly-released version of `regexes.yaml`, from https://raw.githubusercontent.com/ua-parser/uap-core/master/regexes.yaml, `uap-go` panics, by way of `regexp.MustCompile`:

```
panic: regexp: Compile(`Android \d+?(?:\.\d+|)(?:\.\d+|); ([^;]+?)(?: Build|\) AppleWebKit).+?(?<! Mobile) Safari`): error parsing regexp: invalid or unsupported Perl syntax: `(?<`
	goroutine 1 [running]:
	regexp.MustCompile(0xc0000277a0, 0x59, 0xc00095ebe0)
	/usr/local/go/src/regexp/regexp.go:311 +0x152
	github.com/ua-parser/uap-go/uaparser.compileRegex(0x0, 0x0, 0xc0000277a0, 0x59, 0xc00095ebe0)
	...
```
As `regexp` in Golang doesn't support lookarounds of that form.

I see that this project has specifically `uap-core` v0.6.9 as a submodule. Is this on purpose, and is v0.7.0 not supported? (Or conversely, is `uap-core` going to have changes which don't work with `uap-go` from now on?)

**Comment by commenthol** [comment]
Hi @laingawbl yes we had such issues before. They are  had to detect by manual review. Can you please open an Issue or even better a PR in uap-core to fix this?

**Comment by laingawbl** [comment]
OK. I was 50/50 on which project to file it under. Thanks!
